### ISSUE TITLE
Spanish Voice to Text 

### ISSUE THREAD

**Issue by carlostico** [simontelephonics/transcribe-with-azure#3]
Can transcribe.php file transcribe Spanish audio to text? Is there an option to define candidate languages or select a language identification mode within its settings or functionalities?

The English translations are great but the Spanish ones are not good.

**Comment by billsimon** [comment]
Yes, see the URL on line 6 of transcribe.php. At the end of the URL you can change the language. The list of supported languages including national dialects is at https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=stt .

If you want to support both English and Spanish and the US Spanish dialect is acceptable to you then set `es-US` which is noted as being bilingual.
